### ISSUE TITLE
Weird message after Fable upgrade

### ISSUE THREAD

**Issue by forki** [fable-compiler/fable-react_native-demo#15]
I updated this sample to the lastet fable and elmish versions and now see:

![image](https://cloud.githubusercontent.com/assets/57396/22023200/7dde01d6-dcc5-11e6-98dd-5f2243836361.png)

![image](https://cloud.githubusercontent.com/assets/57396/22023207/85a9adfc-dcc5-11e6-860f-a8a663d54efe.png)

/cc @et1975  @alfonsogarciacaro  any ideas?

**Comment by alfonsogarciacaro** [comment]
That's weird, `props` should be passed to the `super` call. Can you post the generated JS for the App component? Or is it in fable-elmish=

**Comment by et1975** [comment]
Hm... this has to be about the root component, let me see if I can reproduce it with elmish samples.

**Comment by forki** [comment]
thx friends. 

(I'm logging this since we see this with out production app as well)

**Comment by et1975** [comment]
Can confirm - this is something fable-compiler does different from the previous release :/

**Comment by et1975** [comment]
Fixed in fable-elmish-react@0.8.1

**Comment by forki** [comment]
💋

**Comment by forki** [comment]
can confirm it's gone.
