### ISSUE TITLE
Linux and macOS support for build platforms

### ISSUE THREAD

**Issue by y2k** [fable-compiler/fable-react_native-demo#16]
In build script build.fsx written absolute win32 path to "C:\Program Files\" etc
https://github.com/fable-compiler/fable-react_native-demo/blob/master/build.fsx

File build.cmd also don't support mono on Linux/maxOS

**Comment by forki** [comment]
There is a build.sh for mono

Am 03.05.2017 9:37 vorm. schrieb "y2k" <notifications@github.com>:

**Comment by y2k** [comment]
I don't see it in master branch. Maybe some other?

**Comment by forki** [comment]
ah you are right. mixed that up with another project. So yes we need to add build.sh one day. similair to https://github.com/fsprojects/ProjectScaffold/blob/master/build.sh

**Comment by alfonsogarciacaro** [comment]
Already supporting Linux and macOS (well, at least I tested it for Mac) :)
