### ISSUE TITLE
Minor tweaks for android and mono

### ISSUE THREAD

**Issue by agrcrobles** [fable-compiler/fable-react_native-demo#35]
Hey there,

Thanks for making a working sample for react native!

Some comments about my experience on `ubuntu` v16.04.

To make it work I had to install fable-compiler globaly in npm ( using yarn and nvm, npm@v3 node@v6.9 )

```
npm i -g fable-compiler
```

Had to update `fable-splitter` project dependency to v0.1.9 it could be related to [this issue](https://github.com/fable-compiler/Fable/issues/1109)

Trying running `build.cmd` didn't work, but `./build.sh` did!! awesome.

**Comment by alfonsogarciacaro** [comment]
Hi @agrcrobles, thanks for your comments! Hmm, strange, the `fable-compiler` npm package shouldn't be needed anymore. And yes, for Linux/macOS you usually should use `build.sh` (this is common in many F# projects), `build.cmd` is Windows-only. BTW, both of the scripts just execute build.fsx which is common for all operating systems.

I'll bump the fable-splitter dependency to 0.1.9, thanks again!

**Comment by agrcrobles** [comment]
great explanation, it is crystal clear!

oh and `fable-compiler` might not be necessary in my environment, I will look into that.
